# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Incredibuilders < Formula
  desc "AI-powered Issue-to-PR pipeline CLI"
  homepage "https://github.com/incredibuilders/incredibuilders"
  version "0.0.1"
  license "SEE LICENSE IN LICENSE"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incredibuilders/incredibuilders/releases/download/v0.0.1/incredibuilders_0.0.1_darwin_amd64.tar.gz"
      sha256 "cf426a822d5ab2f6acaade68b0278f48feed4222d21740170907f16490643165"

      define_method(:install) do
        bin.install "incredibuilders"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incredibuilders/incredibuilders/releases/download/v0.0.1/incredibuilders_0.0.1_darwin_arm64.tar.gz"
      sha256 "2eef0655d682012692fb2e1b4f25495b6c33b8a3a137a65e0d2ab6052b5623e9"

      define_method(:install) do
        bin.install "incredibuilders"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/incredibuilders/incredibuilders/releases/download/v0.0.1/incredibuilders_0.0.1_linux_amd64.tar.gz"
      sha256 "0d33cb7990c20192373fe0f6e5f24d5ba72e3e6358933b110ae5afc338788576"
      define_method(:install) do
        bin.install "incredibuilders"
      end
    end
  end

  test do
    system "#{bin}/incredibuilders", "version"
  end
end
