# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nightgauge < Formula
  desc "AI-powered Issue-to-PR pipeline CLI"
  homepage "https://github.com/nightgauge/nightgauge"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightgauge/nightgauge/releases/download/v0.1.0/nightgauge_0.1.0_darwin_amd64.tar.gz"
      sha256 "122eae77c556fafa89549cf1f9f445e2017cfd4d7862d947683c5b6176ddd3e0"

      define_method(:install) do
        bin.install "nightgauge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightgauge/nightgauge/releases/download/v0.1.0/nightgauge_0.1.0_darwin_arm64.tar.gz"
      sha256 "e5419198e33d147b2110231e53a63a3fac8800d42d5faaace4d7dac2583cc737"

      define_method(:install) do
        bin.install "nightgauge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightgauge/nightgauge/releases/download/v0.1.0/nightgauge_0.1.0_linux_amd64.tar.gz"
      sha256 "c8b431d70afc8455034b25133390840504be1adc9bebf51665abd89087fd08f9"
      define_method(:install) do
        bin.install "nightgauge"
      end
    end
  end

  test do
    system "#{bin}/nightgauge", "version"
  end
end
