# This file was generated by GoReleaser. DO NOT EDIT.
cask "nightgauge" do
  version "0.4.6"

  on_macos do
    on_intel do
      sha256 "5eee244a9da10d2b7960c1b0e7a1855233586ccac7ab53755df51b45f7533c11"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "43fcd48811b73e821d58532c610222cba55312604247f968b547b193b3115fb8"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c7790c5e6f96438fb7cd5156ecb9df44ac7f27ce614843aff1dffc58a251352"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nightgauge"
  desc "AI-powered Issue-to-PR pipeline CLI"
  homepage "https://github.com/nightgauge/nightgauge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nightgauge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nightgauge"]
    end
  end

  # No zap stanza required

end
