# This file was generated by GoReleaser. DO NOT EDIT.
cask "nightgauge" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "65c7a33ba42338ee1c079de2baac844341dfb29b7e299cd90584c5490ba0cda5"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b26bd17d92c42cf96a8eca6ca121b2122cba11c848f14f4d3be2cf5b83fdf6b"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3ab64ab6d9b143000f9499115168c749b1f59db5ece66fc7e793004f359743d"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nightgauge"
  desc "AI-powered Issue-to-PR pipeline CLI"
  homepage "https://github.com/nightgauge/nightgauge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nightgauge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nightgauge"]
    end
  end

  # No zap stanza required

end
