# This file was generated by GoReleaser. DO NOT EDIT.
cask "nightgauge" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "e0db386eab1fe68e1042f29e08ff3cd5b9c790f68f4fbd2e80746e18f7fdede9"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "292e2c684128f5cf0d1e7551e8695445e1a66920a68395d5f93908b81c701431"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b9e5123192156a56bc26be900cdb2367dce6323e021c8541fd68c05f8491c2a"
      url "https://github.com/nightgauge/nightgauge/releases/download/v#{version}/nightgauge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nightgauge"
  desc "AI-powered Issue-to-PR pipeline CLI"
  homepage "https://github.com/nightgauge/nightgauge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nightgauge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nightgauge"]
    end
  end

  # No zap stanza required

end
